---
- name: Install PHP 
  apt: 
    name: "{{ item }}" 
    state: latest
  loop: 
    - php
    - php-mcrypt
    - php-mysql 
    - php-common
    - php-tidy
    - php-xml
    - php-xmlrpc
    - php-mbstring
    - php-memcached
    - php-curl
    - php-zip
    - libapache2-mod-php
  notify:
    - restart apache2

- name: copy info.php
  copy: src=templates/php/info.php dest=/var/www/html/info.php